### ISSUE TITLE
LONG execution 

### ISSUE THREAD

**Issue by golimer** [rundeck/rundeck-cli#315] opened 2020-07-13 11:51 UTC
> time RD_URL=http://127.0.0.1:4440 RD_INSECURE_SSL=true RD_PASSWORD=TEST RD_USER=admin rd system info

real 3m1.046s
user	0m1.284s
sys	0m0.056s`

##**another example** 

>root@rundeck-ble-us-1:/var/log# time RD_URL=http://127.0.0.1:4440 RD_INSECURE_SSL=true >RD_PASSWORD=4SfZiWVNHNa3 RD_USER=admin rd users list
>WARNING: RD_INSECURE_SSL=true, no hostname or certificate trust verification will be performed
>1 Users:
>admin: name [], last Name [], email []

real	3m1.046s
user	0m1.384s
sys	0m0.080s

rd --version
1.3.0

**Comment by gschueler** [comment] 2020-07-14 16:49
seems like a duplicate of #302

**Closed** 2020-07-22 05:31 UTC
